# Default config: https://nikitabobko.github.io/AeroSpace/guide#default-config

config-version = 2
start-at-login = true

# Normalization (https://nikitabobko.github.io/AeroSpace/guide#normalization)
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layout
accordion-padding = 30
default-root-container-layout = 'tiles'     # 'tiles' or 'accordion'
default-root-container-orientation = 'auto'

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Integrations
after-startup-command = ['exec-and-forget sketchybar']
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$AEROSPACE_FOCUSED_WORKSPACE"',
]
[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[gaps]
inner.horizontal = 1
inner.vertical = 1
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-s = 'focus left'
alt-d = 'focus down'
alt-e = 'focus up'
alt-f = 'focus right'
alt-shift-s = 'move left'
alt-shift-d = 'move down'
alt-shift-e = 'move up'
alt-shift-f = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0']

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-space = "layout floating tiling"

[[on-window-detected]]
if.app-id = "org.mozilla.firefox"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "org.alacritty"
run = "move-node-to-workspace 2"
