# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: ""
  language: 'en'
  showRootItemInFileTree: false
git:
  pagers:
    - pager: delta --dark --paging=never
  parseEmoji: true
